// 10 popular cities for every Indian state and union territory
// This list is curated for UX selection; it is not exhaustive or authoritative.

export const CITIES_BY_STATE = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Kakinada",
    "Tirupati",
    "Rajahmundry",
    "Kadapa",
    "Anantapur"
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Tawang",
    "Ziro",
    "Bomdila",
    "Pasighat",
    "Roing",
    "Tezu",
    "Aalo",
    "Namsai"
  ],
  "Assam": [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Sivasagar",
    "Dhubri"
  ],
  "Bihar": [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger"
  ],
  "Chhattisgarh": [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Bhilai",
    "Korba",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Dhamtari",
    "Rajnandgaon"
  ],
  "Goa": [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Cuncolim",
    "Valpoi",
    "Quepem",
    "Sanguem"
  ],
  "Gujarat": [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Nadiad",
    "Morbi"
  ],
  "Haryana": [
    "Faridabad",
    "Gurugram",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula"
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Mandi",
    "Solan",
    "Dharamshala",
    "Kangra",
    "Hamirpur",
    "Una",
    "Bilaspur",
    "Kullu",
    "Chamba"
  ],
  "Jharkhand": [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Hazaribagh",
    "Deoghar",
    "Giridih",
    "Ramgarh",
    "Phusro",
    "Medininagar"
  ],
  "Karnataka": [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Ballari",
    "Shivamogga",
    "Davanagere",
    "Tumakuru",
    "Vijayapura"
  ],
  "Kerala": [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Alappuzha",
    "Palakkad",
    "Malappuram",
    "Kannur",
    "Kottayam"
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Satna",
    "Rewa",
    "Ratlam",
    "Dewas"
  ],
  "Maharashtra": [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Kolhapur",
    "Navi Mumbai"
  ],
  "Manipur": [
    "Imphal",
    "Thoubal",
    "Kakching",
    "Churachandpur",
    "Ukhrul",
    "Senapati",
    "Tamenglong",
    "Bishnupur",
    "Jiribam",
    "Moreh"
  ],
  "Meghalaya": [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongstoin",
    "Williamnagar",
    "Resubelpara",
    "Baghmara",
    "Mairang",
    "Sohra",
    "Khliehriat"
  ],
  "Mizoram": [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Mamit",
    "Lawngtlai",
    "Saiha",
    "Saitual",
    "Hnahthial"
  ],
  "Nagaland": [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Phek",
    "Mon",
    "Kiphire",
    "Longleng"
  ],
  "Odisha": [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Puri"
  ],
  "Punjab": [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Moga",
    "Pathankot",
    "Firozpur"
  ],
  "Rajasthan": [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Udaipur",
    "Ajmer",
    "Alwar",
    "Bharatpur",
    "Bhilwara",
    "Sikar"
  ],
  "Sikkim": [
    "Gangtok",
    "Namchi",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Singtam",
    "Soreng",
    "Pakyong",
    "Yuksom"
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Vellore",
    "Erode",
    "Tiruppur",
    "Thanjavur"
  ],
  "Telangana": [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Siddipet"
  ],
  "Tripura": [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Ambassa",
    "Khowai",
    "Kumarghat",
    "Bishalgarh",
    "Sonamura"
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad"
  ],
  "Uttarakhand": [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Almora",
    "Nainital",
    "Pithoragarh"
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Kharagpur",
    "Haldia",
    "Bardhaman",
    "Malda",
    "Jalpaiguri"
  ],
  // Union Territories
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Garacharma",
    "Prothrapur",
    "Bambooflat",
    "Buniyadabad",
    "Aberdeen Bazar",
    "Rangat",
    "Mayabunder",
    "Diglipur",
    "Campbell Bay"
  ],
  "Chandigarh": [
    "Chandigarh",
    "Mani Majra",
    "Sector 17",
    "Sector 22",
    "Dhanas",
    "Maloya",
    "Hallo Majra",
    "Daria",
    "Kishangarh",
    "Kaimbwala"
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Amli",
    "Samarvarni",
    "Naroli",
    "Dunetha",
    "Kharel",
    "Bhimpore",
    "Marwad"
  ],
  "Delhi": [
    "New Delhi",
    "Delhi",
    "Dwarka",
    "Rohini",
    "Pitampura",
    "Karol Bagh",
    "Saket",
    "Laxmi Nagar",
    "Shahdara",
    "Janakpuri"
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Sopore",
    "Kathua",
    "Udhampur",
    "Kupwara",
    "Pulwama",
    "Rajouri"
  ],
  "Ladakh": [
    "Leh",
    "Kargil",
    "Nubra",
    "Nyoma",
    "Diskit",
    "Turtuk",
    "Drass",
    "Hanle",
    "Tangste",
    "Chuchot"
  ],
  "Lakshadweep": [
    "Kavaratti",
    "Agatti",
    "Amini",
    "Andrott",
    "Minicoy",
    "Kalpeni",
    "Kadmat",
    "Chetlat",
    "Bitra",
    "Kiltan"
  ],
  "Puducherry": [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Oulgaret",
    "Villianur",
    "Ariyankuppam",
    "Bahour",
    "Nettapakkam",
    "Mannadipet"
  ]
};

export function getAllCities() {
  const out = [];
  for (const key of Object.keys(CITIES_BY_STATE)) {
    out.push(...CITIES_BY_STATE[key]);
  }
  return out;
}
